import Layout from '../components/layout'
import '../style/global.css'
import Head from 'next/head'
import { Web3ReactProvider } from '@web3-react/core'
import Web3 from 'web3'

function getLibrary(provider) {
  return new Web3(provider)
}

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>DonateBlock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="images/logo.png" />
      </Head>
      <Web3ReactProvider getLibrary={getLibrary}>
      <Layout>
       <Component {...pageProps} />
      </Layout>
      </Web3ReactProvider>
    </>

  )
}

export default MyApp


