import Layout from '../components/layout'
import '../style/global.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>DonateBlock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="images/logo.png" />
      </Head>
      <Layout>
       <Component {...pageProps} />
      </Layout>
    </>

  )
}

export default MyApp
